import "@mui/material";

export const typography = {
  title: {
    fontFamily: "Inter",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "3em",
    lineHeight: "1em",
  },
  button: {
    fontFamily: "Inter",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "1.125em",
    lineHeight: "1.25em",
  },
  allVariants: {
    color: "#262626",
  },
  overline: {
    fontFamily: "Inter",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "0.875em",
    lineHeight: "1.25em",
  },
  overline2: {
    fontFamily: "Inter",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "0.75em",
    lineHeight: "1.125em",
  },
  overlineRegular: {
    fontFamily: "Inter",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "0.75em",
    lineHeight: "1.125em",
  },
  h1: {
    fontFamily: "Inter",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "1.5em",
    lineHeight: "1.75em",
  },
  h2: {
    fontFamily: "Inter",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "1.5em",
    lineHeight: "1.75em",
  },
  body1: {
    fontFamily: "Inter",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "1.125em",
    lineHeight: "1.5em",
  },
  body2: {
    fontFamily: "Inter",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "1.125em",
    lineHeight: "1.5em",
  },
  bodyRegular: {
    fontFamily: "Inter",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "1em",
    lineHeight: "1.25em",
  },
  bodyMedium: {
    fontFamily: "Inter",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "1em",
    lineHeight: "1.25em",
    Letter: "0.5%",
  },
  bodyMedium2: {
    fontFamily: "Inter",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "0.875em",
    lineHeight: "1.25em",
  },
  caption: {
    fontFamily: "Inter",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "0.875em",
    lineHeight: "1.25em",
  },
  regularCaption: {
    fontFamily: "Inter",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "0.875em",
    lineHeight: "1.125em",
  },
  captionMedium: {
    fontFamily: "Inter",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "0.875em",
    lineHeight: "1.25em",
  },
  caption2: {
    fontFamily: "Inter",
    fontStyle: "normal",
    fontWeight: 500,
    fontSize: "0.875em",
    lineHeight: "1.25em",
  },
  captionRegular: {
    fontFamily: "Inter",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "0.875em",
    lineHeight: "1.25em",
  },
  captionSemibold: {
    fontFamily: "inter",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "12px",
    lineHeight: "16px",
  },
  subtitle1: {
    fontFamily: "Inter",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "1.25em",
    lineHeight: "1.5em",
  },
  subtitle2: {
    fontFamily: "Inter",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "1.25em",
    lineHeight: "1.5em",
  },
  heading1: {
    fontFamily: "Inter",
    fontStyle: "normal",
    fontWeight: 700,
    fontSize: "1.5em",
    lineHeight: "1.75em",
  },
  heading2: {
    fontFamily: "Inter",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: "1.5em",
    lineHeight: "1.75em",
  },
};